### PR TITLE
Blog app: add authorization rules

### PR DESCRIPTION
**Pull request by ShiroYaksha90**
- Install CanCanCan gem.
- Add a `role` column to the users table.
- A user can delete a post if it is theirs or if they have an admin role (column `role` has value `"admin"`). 
- A user can delete a comment if it is theirs or if they have an admin role (column `role` has value `"admin"`).

### CODE REVIEW

**Review by TadesseDev — CHANGES_REQUESTED** [review]
### Hi @ShiroYaksha90 

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request 🛑🛑
yPkfDFf

- [ ] Please be reminded this is a pair programming activity, and for such activities, we expect to see equal collaboration from a team. Please make sure to complete the exercise with your team.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by ShiroYaksha90** [comment]
Hi @TadesseDev, my coding partner already pushed his changes to the project. Kindly explain what more can we do?

**Comment by TadesseDev** [comment]
Dera @ShiroYaksha90, I could not see your partner on the list of collaborators, Besides that Following the commits I fail to open your partner's GitHub profile. Hence I could not confirm his collaboration alongside his profile. Please consider reaching out to senior code reviewers through a `second view on your project`, if you need more assistance and approval of the project review.

**Comment by ShiroYaksha90** [comment]
Thank you @TadesseDev I'll do as you instructed.

**Review by r-ahmed2022 — APPROVED** [review]

**Review by Abenezer-Tilahun — APPROVED** [review]
Hi @ShiroYaksha90 
 
Your project is complete  👍 💯   There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 👏🏻

✔️ No linter errors.
✔️ You used correct Git-Flow.
✔️ Professional README  
✔️ Good Commit Messages.
✔️ Good job for Implemented Blog app: add authorization rules.
## Optional suggestions 
 
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

**Comment by ShiroYaksha90** [comment]
@Abenezer-Tilahun Thank you, have a pleasant day 😃

**Pull request merged**
