### PR TITLE
Blog app: add devise

### PR DESCRIPTION
**Pull request by ShiroYaksha90**
## Hi 👋 , in the PR we :
- Remove `current_user` method in `ApplicationController`.
- [Install and setup devise](https://github.com/heartcombo/devise#getting-started).
  - Can register a new user.
  - User logs in with a combination of email and password.
  - Hashed password should be stored in the database.
  - Ask for confirmation of email.
  - Can reset password.
- [Modify the views in devise](https://github.com/heartcombo/devise#configuring-views) for registration and login to match [the wireframes from the Sneak Peek](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/sneak_peek.md#:~:text=For%20this%20project%20you%20will%20have%20full%20freedom%20in%20terms%20of%20visual%20design%20but%20you%20will%20need%20to%20keep%20the%20following%20wireframes%3A).

### CODE REVIEW

**Review by HAMMAS-SALEEM — COMMENTED** [review]
# Invalid Submission :red_circle:

invalid-submission

## Hey @ShiroYaksha90, @r-ahmed2022 :wave:

Good job on implementing some of the requirements but I cannot proceed review of your pull request because there are some issues that you still need to work on to go to the next project but you are almost there! :blush:

# Optional

_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

# Mandatory Changes ♻️

- [x] It would be nice if you remove the Live Demo section since there is not working live link for your app right now 🤔 So it would be great if you remove the whole Live Demo section 👍

**Review by prolajumokeoni — CHANGES_REQUESTED** [review]
Hi @ShiroYaksha90 and @r-ahmed2022 
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
 - Application allows for registering a new user. ✅ 
 -  `Current_user` method in `ApplicationController` is removed 👏🏿 
  



## Required Changes ♻️
- [ ] Good job so far, kindly make sure that the user can only sign in  successfully when email is confirmed, currently `:confirmable` is enabled in your app, so please ensure that unless a user has confirmed email he can't sign in successfully a message should be shown for the user to go confirm email 👍🏿 
- [ ] Please update styling for sign-in and sign-up page to look like the wireframe 👍🏿
Wireframe Design          |  Your design     
:-------------------------:|:-------------------------:
blog_login (1)  |  127 0 0 1_3000_users_sign_up

- [ ] It will be better to update your app to have the bio, image, comments for post just like in the wireframe, you can add fields for users to add bio and profile image during signup so the fields will not be empty,  see image below 👍🏿 
blog_user_all_posts


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ShiroYaksha90** [comment]
@prolajumokeoni Thank you I'll implement the required changes

**Review by julie-ify — APPROVED** [review]
Hi @ShiroYaksha90 and @r-ahmed2022,

## Highlights!
- Good feature branch name ✔️ 
- No linter errors ✔️ 
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 
- Good code organization and working app ✔️
- Descriptive README ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Status: Approved ✔️ 

Cheers and Happy coding!👏👏👏

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ShiroYaksha90** [comment]
@julie-ify Thank you and have a nice day

**Pull request merged**
